replicasCount: 1
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/notifications
  tag: latest
  pullPolicy: Always

config: {}

service:
  type: ClusterIP
  externalRpcPort: 5005
  internalRpcPort: 5005

autoscaler:
  minCount: 1
  maxCount: 10
  targets:
    targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi

secrets:
  mqUri: ""
  sentryDsn: ""
  sendgridApiKey: ""
  centApiAddr: ""
  centApiKey: ""
